"""Generate bytes from the final decoder using the exact causal transport cache."""
import argparse
import hashlib
import io
import json
from pathlib import Path
import time

import torch

from drrem.core.causal_transport import CausalTransportConfig,CausalTransportMachine
from drrem.core.causal_decode import CausalTransportDecoder
from drrem.core.nondecay_transport import NondecayTransportMachine
from drrem.core.nondecay_decode import NondecayTransportDecoder
from drrem.core.prompt_phase_transport import PromptPhaseTransportMachine,PromptPhaseDecoder
from drrem.core.transport_checkpoint import model_from_protocol
from drrem.core.semantic_flywheel import SemanticFlywheelMachine
from drrem.core.semantic_flywheel_decode import SemanticFlywheelDecoder


@torch.no_grad()
def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--run',type=Path,required=True)
    p.add_argument('--checkpoint',default='best_weights.pt')
    p.add_argument('--prompt',required=True)
    p.add_argument('--out',type=Path,required=True)
    p.add_argument('--bytes',type=int,default=128)
    p.add_argument('--temperature',type=float,default=0.)
    p.add_argument('--seed',type=int,default=701)
    p.add_argument('--device',default='cuda')
    a=p.parse_args();torch.set_num_threads(2)
    if a.bytes<1 or a.temperature<0:p.error('positive byte budget and nonnegative temperature required')
    if a.out.exists():raise FileExistsError(a.out)
    protocol=json.loads((a.run/'protocol.json').read_text())
    raw=(a.run/a.checkpoint).read_bytes();digest=hashlib.sha256(raw).hexdigest()
    ck=torch.load(io.BytesIO(raw),map_location='cpu',weights_only=False);del raw
    m=model_from_protocol(protocol).to(a.device).eval();m.load_state_dict(ck['model'])
    prompt=a.prompt.encode()[-protocol['data']['prompt_max']:]
    if not prompt:p.error('nonempty prompt required')
    ids=torch.tensor(list(prompt),device=a.device)[None]
    synchronous=type(m).forward_states is CausalTransportMachine.forward_states
    if isinstance(m,SemanticFlywheelMachine):
        decoder=SemanticFlywheelDecoder(m,capacity=len(prompt)+a.bytes,precision=protocol['precision'])
        execution='two complete solves; separate per-solve/hop KV; bounded first-solve evidence and trajectory rings'
    elif isinstance(m,PromptPhaseTransportMachine):
        decoder=PromptPhaseDecoder(m,precision=protocol['precision'])
        execution='phase memory with known prompt/response roles; protected prompt='+str(m.prompt_bank_config.protect_prompt)
    elif isinstance(m,NondecayTransportMachine):
        decoder=NondecayTransportDecoder(m,precision=protocol['precision'])
        execution='fixed memory per hop and level: '+m.memory.kind
        if 'content_shift' in protocol:execution+='; content-controlled unitary phase'
        if 'ring_frame' in protocol:execution+='; broad-spectrum unitary rings'
        if 'adaptive_phase' in protocol:execution+='; '+protocol['adaptive_phase']['rule']+' / '+protocol['adaptive_phase']['code']
        if 'query_phase' in protocol:
            execution+='; content-controlled query rotation'
            if protocol['query_phase']['anchor']:execution+='; explicit time reference wave'
    elif synchronous:
        decoder=CausalTransportDecoder(m,capacity=len(prompt)+a.bytes,precision=protocol['precision'])
        execution='per-hop KV cache'
    else:
        decoder=None;execution='full causal prefix for each generated byte'
    def full_prefix():
        with torch.autocast(torch.device(a.device).type,dtype=torch.bfloat16,enabled=protocol['precision']=='bf16'):
            return m(ids)[:,-1,0].float()
    generator=torch.Generator(device=a.device).manual_seed(a.seed)
    start=time.perf_counter();logits=decoder.prefill(ids)[:,-1,0].float() if decoder else full_prefix();tokens=[]
    for i in range(a.bytes):
        chosen=logits.argmax(-1) if a.temperature==0 else torch.multinomial((logits/a.temperature).softmax(-1),1,generator=generator).squeeze(-1)
        tokens.append(int(chosen))
        if i+1<a.bytes:
            if decoder:logits=decoder.step(chosen)[:,0,0].float()
            else:ids=torch.cat((ids,chosen[:,None]),1);logits=full_prefix()
    generated=bytes(tokens)
    result={'checkpoint_sha256':digest,'step':ck['step'],'seen_response_bytes':ck['seen_response_bytes'],
        'prompt':prompt.decode(errors='replace'),'generated':generated.decode(errors='replace'),
        'generated_hex':generated.hex(),'temperature':a.temperature,'seed':a.seed,
        'execution':execution,
        'seconds':time.perf_counter()-start,'scope':'generation sample; not an evaluation loss; fixed length because no EOS byte is trained'}
    a.out.parent.mkdir(parents=True,exist_ok=True);a.out.write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n')
    print(json.dumps(result,ensure_ascii=False),flush=True)


if __name__=='__main__':main()
